<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>$(MSBuildProjectName)-0.002</AssemblyName>
    <ApplicationIcon>xnc_logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xnc_logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>

</Project>
